import requests
import csv
import numpy as np
import logging
import json

file_route = "scripts/movies.csv"

URL = "http://127.0.0.1:5000/api/movies/add"


title = [
    "Mission: Impossible - Dead Reckoning Part One",
    "Oppenheimer",
    "The Exorcist",
    "Get Out",
    "Saw",
    "John Wick: Chapter 4",
    "The Nightmare Before Christmas",
    "Spider-Man: Across the Spider-Verse",
    "Halloween",
    "Dune",
    "Past Lives",
    "Guardians of the Galaxy Vol. 3",
    "The Wolf of Wall Street",
    "The Shawshank Redemption",
    "Harry Potter and the Sorcerer's Stone",
    "The Shining",
    "The Godfather",
    "Interstellar",
    "The Batman",
    "The Dark Knight",
    "Everything Everywhere All at Once",
    "The Thing",
    "The Silence of the Lambs",
    "Titanic",
    "Pulp Fiction",
    "Fight Club",
    "Top Gun: Maverick",
    "Alien",
    "Inception",
    "Gladiator",
    "Coraline",
    "Blade Runner 2049",
    "The Lord of the Rings: The Fellowship of the Ring",
    "American Beauty",
    "Once Upon a Time in Hollywood",
    "Pride & Prejudice",
    "Joker",
    "The Big Short",
    "The Departed",
    "Se7en",
    "Heat",
    "No Country for Old Men",
    "American Psycho",
    "Ghostbusters",
    "Inglourious Basterds",
    "The Gentlemen",
    "The Princess Bride",
    "Black Swan",
    "The Goonies",
    "Schindler's List",
    "Parasite",
    "Sicario",
    "Requiem for a Dream",
    "The Whale",
    "Prisoners",
    "Gone Girl",
    "Blade Runner",
    "Goodfellas",
    "The Prestige",
    "Back to the Future",
    "Taxi Driver",
    "Whiplash",
    "The Matrix",
    "Rosemary's Baby",
    "Django Unchained",
    "Spider-Man: No Way Home",
    "Mad Max: Fury Road",
    "Forrest Gump",
    "The Others",
    "Saving Private Ryan",
    "Avengers: Endgame",
    "Harry Potter and the Goblet of Fire",
    "Jurassic Park",
    "Knives Out",
    "Stand by Me",
    "Scarface",
    "Donnie Darko",
    "Come and See",
    "Psycho",
    "Star Wars: Episode IV - A New Hope",
    "Mission: Impossible - Fallout",
    "LÃ©on: The Professional",
    "Man on Fire",
    "Young",
    "Frankenstein",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Rogue One: A Star Wars Story",
    "Oldboy",
    "Ford v Ferrari",
    "Jaws",
    "The Lord of the Rings: The Return of the King",
    "The Green Mile",
    "Catch Me If You Can",
    "Shutter Island",
    "The Dark Knight Rises",
    "Good Will Hunting",
    "The Handmaiden",
    "12 Angry Men",
    "The Banshees of Inisherin",
    "The Usual Suspects",
]

rating = [
    "7.9",
    "8.5",
    "8.1",
    "7.8",
    "7.6",
    "7.8",
    "7.9",
    "8.7",
    "7.7",
    "8.0",
    "8.0",
    "7.9",
    "8.2",
    "9.3",
    "7.6",
    "8.4",
    "9.2",
    "8.7",
    "7.8",
    "9.0",
    "7.8",
    "8.2",
    "8.6",
    "7.9",
    "8.9",
    "8.8",
    "8.3",
    "8.5",
    "8.8",
    "8.5",
    "7.7",
    "8.0",
    "8.8",
    "8.3",
    "7.6",
    "7.8",
    "8.4",
    "7.8",
    "8.5",
    "8.6",
    "8.3",
    "8.2",
    "7.6",
    "7.8",
    "8.4",
    "7.8",
    "8.0",
    "8.0",
    "7.7",
    "9.0",
    "8.5",
    "7.7",
    "8.3",
    "7.7",
    "8.1",
    "8.1",
    "8.1",
    "8.7",
    "8.5",
    "8.5",
    "8.2",
    "8.5",
    "8.7",
    "8.0",
    "8.5",
    "8.2",
    "8.1",
    "8.8",
    "7.6",
    "8.6",
    "8.4",
    "7.7",
    "8.2",
    "7.9",
    "8.1",
    "8.3",
    "8.0",
    "8.4",
    "8.5",
    "8.6",
    "7.7",
    "8.5",
    "7.7",
    "8.0",
    "8.1",
    "7.8",
    "8.4",
    "8.1",
    "8.1",
    "9.0",
    "8.6",
    "8.1",
    "8.2",
    "8.4",
    "8.3",
    "8.1",
    "9.0",
    "7.7",
    "8.5",
]


description = [
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
    "lorem ipsum",
]
image = [
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
    "image_url",
]


data = {"title": title, "rating": rating, "description": description, "images": image}


def run_script():
    try:
        requests.post(URL, json=data)
    except Exception as e:
        logging.error(e)


if __name__ == "__main__":
    run_script()
